<?php

/**
 * @file
 * Blätter Export for ePub generation.
 */

/**
 *  Implements hook_mail().
 *
 * This hook defines a list of possible e-mail templates that this module can
 * send. Each e-mail is given a unique identifier, or 'key'.
 *
 * $message comes in with some standard properties already set: 'to' address,
 * 'from' address, and a set of default 'headers' from MailManager::mail(). The
 * goal of hook_mail() is to set the message's 'subject' and 'body' properties,
 * as well as make any adjustments to the headers that are necessary.
 *
 * The $params argument is an array which can hold any additional data required
 * to build the mail subject and body; for example, user-entered form data, or
 * some context information as to where the mail request came from.
 *
 * Note that hook_mail() is not actually a hook. It is only called for a single
 * module, the module named in the first argument of MailManager::mail(). So
 * it's a callback of a type, but not a hook.
 *
 * @param string $key     The key of the message
 * @param array  $message The message array
 * @param array  $params  The params array
 *
 * @return void
 */
function blaetter_export_epub_mail(string $key, array &$message, array $params)
{
    $options = [
        'langcode' => $message['langcode'],
    ];
    $headers = [
        'MIME-Version'              => '1.0',
        'Content-Type'              => 'text/html; charset=UTF-8; format=flowed; delsp=yes',
        'Content-Transfer-Encoding' => '8Bit',
        'X-Mailer'                  => 'Drupal',
        'From'                      => $params['from'],
        'Sender'                    => $params['from'],
        'Return-Path'               => $params['from'],
    ];

    switch ($key) {
        case 'mobi_mail':
            foreach ($headers as $key => $value) {
                $message['headers'][$key] = $value;
            }
            $message['from'] = $params['from'];
            $message['subject'] = $params['subject'];
            $message['body'][] = $params['body'];
            $message['files'][] = $params['files'];
            break;
    }
}
